spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080
